{%set name = "pyflakes" %}
{%set version = "1.4.0" %}
{%set hash_type = "sha256" %}
{%set hash_val = "05c8a1702088e9b54acb422f78210afc6074b3472afa7a0a77f0b8aa3f5db605" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - {{ name }}

about:
  home: https://github.com/PyCQA/pyflakes
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Pyflakes analyzes programs and detects various errors.'
  dev_url: https://github.com/PyCQA/pyflakes

extra:
  recipe-maintainers:
    - jakirkham
    - sigmavirus24
    - dopplershift
    - ocefpaf
