{% set name = "pyflakes" %}
{% set version = "4.0.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dcf9cfcece3d9dacc66b7dd2fa217c1a1b79e3075bf488909c15e0857203fd24

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - pyflakes = pyflakes.api:main

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - pyflakes
    - pyflakes.api
    - pyflakes.checker
    - pyflakes.messages
    - pyflakes.reporter
    - pyflakes.scripts
    - pyflakes.test.harness
    - pyflakes.test.test_imports
    - pyflakes.test.test_other
    - pyflakes.test.test_undefined_names
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pyflakes --help
    - pytest --pyargs pyflakes.test -v

about:
  home: https://github.com/PyCQA/pyflakes
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pyflakes analyzes programs and detects various errors.
  description: |
    Pyflakes analyzes programs and detects various errors. It works by parsing
    the source file, not importing it, so it is safe to use on modules with side
    effects. It is also much faster.
  dev_url: https://github.com/PyCQA/pyflakes
  doc_url: https://pypi.org/project/pyflakes/

extra:
  recipe-maintainers:
    - jakirkham
    - sigmavirus24
    - dopplershift
    - ocefpaf