{%set name = "pyflakes" %}
{%set version = "1.5.0" %}
{%set hash_type = "sha256" %}
{%set hash_val = "aa0d4dff45c0cc2214ba158d29280f8fa1129f3e87858ef825930845146337f4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - {{ name }}

about:
  home: https://github.com/PyCQA/pyflakes
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Pyflakes analyzes programs and detects various errors.'
  description: |
    Pyflakes analyzes programs and detects various errors. It works by parsing
    the source file, not importing it, so it is safe to use on modules with side
    effects. It is also much faster.
  dev_url: https://github.com/PyCQA/pyflakes
  doc_url: https://pypi.python.org/pypi/pyflakes
  doc_source_url: https://github.com/PyCQA/pyflakes/blob/master/README.rst

extra:
  recipe-maintainers:
    - jakirkham
    - sigmavirus24
    - dopplershift
    - ocefpaf
