travis:
  secure:
    BINSTAR_TOKEN: TECRg6dEsSik/GYXtwkBw0G0Rq1KJaIehEYiwZ5IS3YYkaUyXyQ7im4MLnIVWlKMqpC5qTZjT968r+HyDzlDmLVUN/rPLylKyJB4ZR5H49PzUsmBBAj4qNUf5V6Kw4hysbPoYIjsimOd6jtU+UlXOcDYIvuB9oPpe+BURNm9dxdRxRLxgjnjIXDYWZW6B7XgcictW0AIz+6KGt65G7UiU0pxsesh5AMrSWQClThtnDV5dHzAvN6Y5dza5GoitEBgyaL+UAGO1OE8yEYmaknOsfHUIzLkZjucVR8rXKex/Em9J/IOM7OnRtjF621YVJKWU2zyuGBxby6hCBQaf2GAC4eH6yNrRm1e9zSoAgxoIlfWnZXlNc/19wqEeo3HkqklRP9v0HkZ/9y/nanx1oWMg6/SdlqpveUYcv4tBUJleMBiOCc9n30YPQhP2FoGS1ZzqYxcnLaIVMfcrEM3wHaJs1F1Pn9fGmnLHIHEnw+c26yyYIhl23JNjojsWzCKZ+sFa6r/s+T4iJ8e4lFYARU9eCuCkAGEqP/auvuMDVzn3HvnCp3jVAgoGo8ZjxuBYgYd3aClJOncAyr3L1oIbW/lqi9QhF1w72kGU48VO7yF9+huzEiTU+BjqhDpUbGh97W4RXFmaVA2VFzTI09tu8BTX0seZJQtKrbwrq5KO911UGA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
