travis:
  secure:
    BINSTAR_TOKEN: 3qvFwnY1JuR5+kydEgVZqx7zIVYCmuOJZqOC/Xj0G87rE3S4MjlQaGHIsk4kg+gXLxphCfXirs7Vv7Dyk8IXy6lcXdiZDRuI5REGrOg15wuXua8i5TeiFVM6M9da/hxmlFXp4snUUacspomOuWmWwk/+b0/xQyCxA8LYmlMvbSiEXqvI+ZgF1A/vFE4+by3W5i2ySUI6CvHv9yGUPZePViEjqISCqff7kJcqH5H5ox2EYQU9ca3FivR+kOLqDoKI0n7gato9WWE6giTeF0QyjH37EgxmqMTcjfpHg28TpUIQY8eKmZhtl1ijtcKqj6IKaiwYlxMdGppWOIhSaV9Qomq1j+MDeHrk/ZE/xF06g6RX3gWxmznfwld+0N1gpYERz365yevkcJkmXVm5DT+NGHN/uHOHdXkEWoa2LMwlj1DvC+j5KHnqs4TtgdQVtOv+M/xsPjD5OmL9vcRqMthVhmq9m9pcLg6DOyHJpKEPK9Q9MxPAALbfySfQ33FCtENDwGWpy88cJh81tO6r94FA7eI9mD8BG1RMMqxOL+NBCgGBjySdijpoVfiITgxGMQwVO36QZie01sprAHeB73skrmdEsJqjNe5xpNcgu0y+Sq3P7IhMJTufl4wlYKGMACJ4en9mb4laxWbWRL1Q/ldtfAFt9xIJBCXSFxxAS4EvEpM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
